title: Avinash's Website
theme: minima
author: Avinash Iyer
description:
  I'm a math and econ major at Occidental College. Welcome to my website!
header_pages:
  - blog.md
  - opinions.md
  - homeworks.md
