title: Avinash Iyer's Website
theme: minima
author: Avinash Iyer
description:
  I'm a math and econ major at Occidental College. Welcome to my website!
header_pages:
  - blog.md
  - adventofcode.md
  - No-Starch-Press-R-Workthrough.html
