title: Avinash Iyer
author:
  name: Avinash Iyer
  email: iyera@oxy.edu
theme: minima
description:
  I'm a math and econ major at Occidental College. Welcome to my website!
header_pages:
  - README.md
  - blog.md
  - adventofcode.md
